### PR TITLE
urlsafe base64 encoding

### PR DESCRIPTION
**Pull request by theromis**

### CODE REVIEW

**Comment by dchest** [comment]
What's the rationale for this breaking change (apart from saving up to 4 bytes)?

**Comment by theromis** [comment]
@dchest `=` is not url save symbol and it should be url escaped, this way of calling it just avoids potential url problems.

**Comment by dchest** [comment]
@theromis it's allowed in cookies though.

**Comment by theromis** [comment]
preparing new PR

**Pull request closed without merging**
